### ISSUE TITLE
Create capitalization/verbiage data structure for a11y strings? 

### ISSUE THREAD

**Issue by twant** [phetsims/molarity#107]
As @zepumph and I have been working on Molarity, we've discovered many instances where, for grammatical correctness, we need to create a capitalized or lowercase version of a string that's used in multiple places, or create a version of the string that may use slightly different verbiage (for example, we need to fill in the string "beaker {{volume}}" to be both "beaker is half full" and "beaker half full" in different places in the descriptions. We think it may be helpful to create a data structure that allows these different versions to be created/accessed without needing to create several different strings -- this may be a helpful for more than just Molarity or GFLB. @jessegreenberg what do you think?

**Comment by jessegreenberg** [comment]
Thanks @twant, this does sound useful. One thing that will be tricky is thinking ahead to i18n. Say we need to have both "beaker half full" (segment) and "Beaker half full." (sentence). A utility function like `fragmentToSentence` that capitalizes the first letter and adds a period would make sense for english, but I am not sure if it would work for all languages.

So far, we have just included multiple strings like "beaker {{volume}}" and "beaker is {{volume}}" so that a translator can order words in the right way for their language.

**Comment by jessegreenberg** [comment]
It would still be good to discuss at next meeting, then we could decide whether to work on this further and move to phetcommon (or somewhere else if that repos is to be removed someday).

**Comment by terracoda** [comment]
@twant, @zepumph, and @jessegreenberg, I agree that it would be wonderful to automate sentence capitalization and final periods. I think the most efficient way to do this is with regular expressions (this topic has come up before, and more than once). 

**Please keep in mind the following:**
- we often do NOT use "standard" complete sentences, leaving out "the's" and "is's" (and other small words) here and there.
- for this sim, there were some early capitalization issues because examples in the design doc were not using (at least not always using) correct sentence capitalization.
- in GFL Basics Lessons Learned section, I mentioned that I addressed capitalization- and period-issues in that sim, by removing these on `aria-valuetext` (i.e. values in object responses) (exceptions would be any proper names, none in that sim), and to use sentence capitalization (and period at end) only in alerts (i.e., context responses)

I hope these are helpful considerations.

**Comment by terracoda** [comment]
Also, for this sim, I think we should get the new scales in and the new phrases in before we try to address this issue.

**Comment by terracoda** [comment]
@twant and @zepumph, I think we should try removing capitalization on all the `aria-valuetext` phrases and parameters, i.e., the strings that show up in the values for the two sliders.

And then for the screen summary and Play Area beaker descriptions, there seems to be a single just capitalized "Is" in the second bullet that described saturation in the Play Area beaker description. If you remove the capital on that one "Is" and remove capitalization on the slider values (`aria-valuetext`) then we only need to be looking at the phrases in the alerts.

<img width="826" alt="caps-issue" src="https://user-images.githubusercontent.com/1902116/60881052-31980400-a245-11e9-9992-a763f121e6e8.png">
<img width="715" alt="caps-issue-eg2" src="https://user-images.githubusercontent.com/1902116/60881057-33fa5e00-a245-11e9-8a04-6b429b10b74e.png">

**Comment by zepumph** [comment]
I think @terracoda's above recommendations for capitalization sound nice. Over to @twant to implement and/or discuss further with designers.

**Comment by zepumph** [comment]
As for a general tool. So far @terracoda has been very good at designing around the need for this in most cases (@twant let me know if you disagree). If we come across a place in the future where a Type deserves creation, we should handle it there. Removing from meeting.

**Comment by twant** [comment]
I think this one slipped through the cracks for me -- so sorry about that! I just implemented this capitalization structure for the aria-valuetext (I think the other items have already been fixed in other issues). Assigning over to you @terracoda to double check if you have a chance along with the once-over you and @Matthew-phet are doing with Molarity pre-dev testing!

**Comment by terracoda** [comment]
Ok, on it!

**Comment by terracoda** [comment]
@twant, I played with Molarity quite a bit in the A11y View and I do not see any capitalization issues. I do see a couple of punctuation issues (alerts and 1 in pdom) and spacing issues (in alerts only). I will make new issues for those items.

**Comment by terracoda** [comment]
Closing this one :-)
