### ISSUE TITLE
Help with assertions? 

### ISSUE THREAD

**Issue by twant** [phetsims/molarity#141]
@zepumph as I'm working through my self review, I am working on this item: 

- [ ] Assertions should be used appropriately and consistently. Type checking should not just be done in code comments. Use Array.isArray to type check an array.

I'm not sure of all of the times when it's appropriate/necessary to use an assertion. I'm wondering if you can review one of the describers (maybe ConcentrationDescriber) and flag the places where an assertion seems appropriate -- I can then use that as an example for other files. Happy to save this as an item to work through together at our next meeting, as well!

**Comment by zepumph** [comment]
I would say that in general this should be something that shouldn't be overthought. In general, I think that there should always be an assertion whenever you are making an assumption about something. In sim specific code you don't have to spend too much time asserting the types of function parameters, but in general common code we do that a lot (see the top of `Utterance.js`).

>`assert && assert( newValue !== oldValue, 'unexpected: called with no change in concentration' );` 
  - [ ]  This is covered for you in the implementation of Property. See `Property.set()` line 172 of my working copy. Notice how there is a check to make sure the new value is different before calling `notifyListeners` (which is was calls (lazy)linked listeners). I would go ahead and remove this.

- [ ] At the end of `concentrationToIndex` and `solidsToIndex` you have an `else` statement making an assumption about what the concentration is. What I would do is either add an assertion in that else making sure that that value is as expected (within the "6 index" range), OR change it to an `else if` and then add `assert && assert( false, 'we should not get here but with a better message' )` after the conditional. See `GravityForceLabPositionDescriber.getDistanceIndex` for an example of the latter.

- [ ] `getSolidsChangeString` has what I think is a good assertion, but it doesn't have a message. In general the only reason I would leave out an assertion message is because I am type checking a parameter and it is obvious, like `assert && assert( typeof myNumber === 'number' );` 

- [ ] `failed: ` is not necessary, because `Assertion failed: ` is tacked on to the beginning of assertion errors, see `assert/js/assert.js:20`

- [ ] I would take a pass and just see if any more assertions could be added easily. I couldn't see anything obvious.

Good work! Let me know if you have any questions.

**Comment by twant** [comment]
@zepumph Thanks so much for these comments! They were very helpful. I've done a pass through to add a few more assertions & clean up the old ones. Assigning back over to you for review!

**Comment by zepumph** [comment]
>      assert && assert( this.precipitateAmountProperty.value > 0, 'precipitateAmountProperty should be greater than 0');


This is totally acceptable, and I have written many assertions like this. If we are really splitting hairs I would say an A+ assertion here would tell me why it is expected to be greater that zero. Though this may be a bad example because it is a bit obvious. For example, in one assertion asserts greater than zero, but then in `solidsToIndex` it asserts greater than or equal to zero. Why is that?

Otherwise looks really nice.

**Comment by twant** [comment]
Thanks for these comments @zepumph! Just pushed changes -- closing this issue.
