### ISSUE TITLE
Test for memory leaks prior to a11y publication

### ISSUE THREAD

**Issue by twant** [phetsims/molarity#143]

**Comment by twant** [comment]
Both tests were conducted over a period of 4 hours, taking snapshots every 15 - 60 mins. 

PhET-iO:
![Memory Leak Test PhET-iO](https://user-images.githubusercontent.com/12232821/64480282-9d311b80-d179-11e9-8a33-28115fa7017e.png)

Regular sim: 
![Memory Leak Test ](https://user-images.githubusercontent.com/12232821/64480283-9d311b80-d179-11e9-99da-cdf44cee889b.png)

@zepumph can we discuss these results in our next meeting?

**Comment by zepumph** [comment]
Yes a discussion sounds good. First off, these numbers all look great, and we probably don't need to do anything else here. But for learning's sake:

Did you by change save the snapshot data, or look into comparing earlier snapshots to later ones? I only mention because it can be very valuable to compare from a fuzz of about 5 minutes, to one a while later, to see what junk has been accumulated. From there looking for Molarity-specific types whose numbers seem to be growing.

A brief discussion of any questions seems good before a close.

**Comment by twant** [comment]
TODO: fuzz for 15 min and compare snapshots 2 & 3 (not on startup) to look for anything piling up.

**Comment by twant** [comment]
@zepumph Interesting development in this...when I went back to more closely examine the heap snapshots, I got very different test results. I took snapshots every 5 min, and each time it went up by at least 10MB. I've saved a couple of the snapshots. 

I'm currently taking a look to see if I can figure out, but wanted to flag that we should probably discuss on Tuesday!

**Comment by twant** [comment]
Update: two largest (and growing) sections are closure and HTMLDocument.

**Comment by twant** [comment]
False alarm, was looking at the a11y view in this process! Just tested again and saw no evidence of a memory leak. Closing!
