### ISSUE TITLE
MolarityAlertManager review

### ISSUE THREAD

**Issue by zepumph** [phetsims/molarity#184]
- [x] Together (if I remember correctly) we set up the alert manager as a singleton with an `initialize` function. Do you prefer `wireUpListeners` instead of `initialize`? I am on the fence. I guess `initialize` better because it cues more clearly that this should only be called once. I'm going to check this off, as it is good as it, but I will keep it here in case you have any thoughts.
- [x] Every value that is set to `this` in initialize needs to be set in the constructor, even if it is just to `null`. This is mainly for coding conventions, but it also helps performance (though that is likely moot here). I would move the utterance declarations totally up to the constructor, and just set the parameters to null until initialized and document that they are set in the initialize method.

- [x] With just a bit of refactoring, we can factor out the guts of the listeners for volumeProperty and soluteAmountProperty into a shared function. Here is a first pass at this. It just involves having their respective describers adhere to a specific api:
   ```js
    alertValueChanged( describer ) {

      // A special alert is read out if the solution is saturated without any solids. If the solution is newly
      // saturated or newly unsaturated, an alert is read out. The text depends on whether descriptions are
      // qualitative or quantitative, and if there is any solute in the beaker.
      if ( this.concentrationDescriber.isExactlySaturated() ) {
        this.alertMaxConcentration();
      }
      else if ( this.concentrationDescriber.saturationStateChanged() ) {
        this.alertNewSaturation();
      }
      else if ( !this.solution.hasSolute() ) {
        this.alertNoSolute( this.useQuantitativeDescriptionsProperty );
      }
      else if ( this.useQuantitativeDescriptionsProperty.value ) {
        this.alertSliderQuantitative();
      }
      else {
        this.alertSliderQualitative( describer.getChangeStrings(), describer.getRegionChanged() );
      }
    }
   ```
  Then usages will just be:
   ```js
      solution.soluteAmountProperty.lazyLink( () => this.alertValueChanged( soluteAmountDescriber ) );
      solution.volumeProperty.lazyLink( () => this.alertValueChanged( volumeDescriber ) );

   ```
   You should just be able to rename the "changeStrings" function to be consistent for both describers, and then have a getter for the "region changed" value do the same. Don't forget to document in both describers the need for them to be kept the same! UPDATE: I'm going to commit what I have right now, but it may need some cleanup. Please review my commits below (https://github.com/phetsims/molarity/commit/490832a208a0d04269438a7c2a83b38ac4be33e1).

- [x] In addition to reviewing the work I did above, please rename `alertValueChanged` to a method that seems better to you (if you think one does).
- [x] Even though each conditional line in `alertValueChanged` is pretty clearly named with a method, I thnk it may be nice to have a comment line for each one, just so you don't have to go hunting down each method to get an idea of the type of alert that fires for each. This method feels worthy of some "over documentation" since it basically is 90 percent of the alerts in the simulation.
- [ ] `alertNewSaturation` calls `utteranceQueue.clear`. Can you speak to why this is needed? The doc says "to remove utterances from previous saturation region," but I thought that was the purpose of having a reusable `saturationUtterance` that is reset. When that utterance is reused the utteranceQueue clears out any previous references that utterance has in the queue. Does that make sense? Can we delete this usage of `clear`?

>     * @param {boolean} quantityChange - true if the quantity has increased, false if quantity has decreased

- [x] This param for `alertSliderQualitative` is confusing to me. (1) the quantity will have changed if it decreased, so if nothing else changes I think it deserves a rename. (2) Is a boolean the best way to represent this? What if the value hasn't changed at all? If that is impossible then documentation should be adjusted to communicate that. (3) I actually think the doc may just be wrong, which is why I'm confused. Please help me.
- [x] `ConcentrationDescriber.getConcentrationState`can be simplified (and probably renamed) because it is only called from qualitative descriptions from `alertSliderQualitative`. It looks like we won't get rid of `quantitativeConcentrationStatePattern` though because it is being used elsewhere. I implemented this one and renamed to `getQualitativeConcentrationState`, please review below (https://github.com/phetsims/molarity/commit/ee0013ae813bad064797cb09d4646650a00f9633).
- [x] In `alertSliderQualitative` `stateInfo` is only used if the solution is not saturated. I'm going to refactor stateInfo so that it is only set when needed. Please review this well as I don't have a good grasp of when the state info should be included (https://github.com/phetsims/molarity/commit/2453610921223e5cd394811ae58283a3fcf6bfe5).
- [x] I would rename the string `qualitativeConcentrationStatePattern` to `qualitativeConcentrationStateClausePattern`, because it includes punctuation to make that alert formatted correctly. It is not just the concentration "state". 
* In general I think that `alertSliderQualitative` and `alertSliderQuantitative` are in good shape. I like the general pattern of splitting on quantitative/qualitative and then to saturated/not. I think it works well and looks classy.

**Comment by zepumph** [comment]
Review complete of this file. Over to you @twant.

**Comment by twant** [comment]
@zepumph I reviewed the items you mentioned, and they both seem to be working well. Thanks for doing that! 

Additionally, I updated the parameter for `alertSliderQualitative` to be named `quantityRegionChanged` and updated the doc (which you're right, was just incorrectly describing the parameter)

**Comment by twant** [comment]
- [ ] alertNewSaturation calls utteranceQueue.clear. Can you speak to why this is needed? The doc says "to remove utterances from previous saturation region," but I thought that was the purpose of having a reusable saturationUtterance that is reset. When that utterance is reused the utteranceQueue clears out any previous references that utterance has in the queue. Does that make sense? Can we delete this usage of clear?

For `alertNewSaturation`, the original reason this calls `utteranceQueue.clear()` is that adds `saturationUtterance` to the queue, but `sliderUtterance` may also be in the queue (and likely is, since adjusting the sliders is the most common way to change the saturation). When we reach saturation, we want the `saturationUtterance` to take priority, even if there are old `sliderChange` alerts in the queue. 

However, I just tested with and without this line (moving the sliders at all different speeds and increments), and I'm not seeing a difference in behavior. I feel good about removing this one, and will remove now.

**Comment by zepumph** [comment]
>However, I just tested with and without this line (moving the sliders at all different speeds and increments), and I'm not seeing a difference in behavior. I feel good about removing this one, and will remove now.

Understood. I also see that `addToFront` is likely helping it working in this way.

>but `sliderUtterance` may also be in the queue (and likely is, since adjusting the sliders is the most common way to change the saturation). 

If that is the utterance you are worried about. I would recommend removing that utterance from the queue if it is in there. We would need to add a method to UtteranceQueue, but that can be done. What do you think about this in `alertNewSaturation`? It feels very explicit.
```js
if( utteranceQueue.hasUtterance(this.sliderUtterance)){
  utteranceQueue.removeUtterance( this.sliderUtterance);
}
```

**Comment by twant** [comment]
found out why the utteranceQueue needs to be cleared! alertMaxConcentration modifies the sliderUtterance, and so if you don't clear the queue its possible to get the alerts out of order. Clearing the queue ensures that atMaxConcentration gets skipped if necessary. 

I added back in clear() for now, along with the condition you suggested. Let me know how you feel about leaving it like this vs. adding the removeUtterance to UtteranceQueue.

**Comment by twant** [comment]
Okay, I think these three items are ready for review, and then this issue should be done! Over to you to review, @zepumph 

- [ ]  In addition to reviewing the work I did above, please rename alertValueChanged to a method that seems better to you (if you think one does).
- [ ]  Even though each conditional line in alertValueChanged is pretty clearly named with a method, I thnk it may be nice to have a comment line for each one, just so you don't have to go hunting down each method to get an idea of the type of alert that fires for each. This method feels worthy of some "over documentation" since it basically is 90 percent of the alerts in the simulation.
- [ ]  alertNewSaturation calls utteranceQueue.clear. Can you speak to why this is needed? The doc says "to remove utterances from previous saturation region," but I thought that was the purpose of having a reusable saturationUtterance that is reset. When that utterance is reused the utteranceQueue clears out any previous references that utterance has in the queue. Does that make sense? Can we delete this usage of clear?

**Comment by zepumph** [comment]
I do not like clearing here. To me it is in breach (albeit only minorly) of the factor that MolarityAlertManager does not own UtteranceQueue, and as a general pattern should not assume that it knows exactly what is inside it, and as a result shouldn't clear it. For example, what if the sim was reset, and that alert was in the queue, but for some reason this alert fired before the reset alert could be released, that feels buggy.

It is the most maintainable to take the explanation you mentioned in https://github.com/phetsims/molarity/issues/184#issuecomment-565272834 and handle it directly. I think that likely means removing the sliderUtterance or somehow blocking it in another way. Let me know if would like to talk further about that.

**Comment by zepumph** [comment]
@twant and I worked on this and agreed that `removeUtterance` was a better idea than `clear`. Added above. Closing
