### ISSUE TITLE
Long String Test

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/molarity#21]
Test device: Mac 

Operating System: OS X 10.10.5

Browser: Safari 9.0

Problem description: Upper part of the beaker is shifted out of the screen when the Extremely Long String Test is performed.

Steps to reproduce: Standard Extremely Long String Test

Severity:

Screenshots: 
![screen shot 2015-10-07 at 10 19 11 am](https://cloud.githubusercontent.com/assets/12610678/10343870/68725fe4-6cdd-11e5-8158-cefea620d24f.jpg)

Normal: 
![screen shot 2015-10-07 at 10 23 31 am](https://cloud.githubusercontent.com/assets/12610678/10343886/8378bb12-6cdd-11e5-8339-41f52c471e82.jpg)

Troubleshooting information (do not edit):
Name: SomeExtremelyLongStringThatWouldLikelyBreakAnythingDoubleDidNotExpose
URL: http://www.colorado.edu/physics/phet/dev/html/molarity/1.2.0-rc.1/molarity_en.html?stringTest=SomeExtremelyLongStringThatWouldLikelyBreakAnythingDoubleDidNotExpose
Version: 1.2.0-rc.1 2015-10-01 21:51:38 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.1.56 (KHTML, like Gecko) Version/9.0 Safari/601.1.56
Language: en-us
Window: 1240x667
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (2.1 INTEL-10.6.33)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"858e65ac","branch":"master"},"axon":{"sha":"90798ec9","branch":"master"},"babel":{"sha":"931afbf1","branch":"master"},"brand":{"sha":"f2c42d7b","branch":"master"},"chipper":{"sha":"fc81a64e","branch":"master"},"dot":{"sha":"428a9836","branch":"master"},"joist":{"sha":"4a72198b","branch":"master"},"kite":{"sha":"fe8d3c5c","branch":"master"},"molarity":{"sha":"f5c4d5b3","branch":"1.2"},"nitroglycerin":{"sha":"9d8393fa","branch":"master"},"phet-core":{"sha":"8e31808c","branch":"master"},"phetcommon":{"sha":"acbbf59b","branch":"master"},"scenery":{"sha":"317e459d","branch":"master"},"scenery-phet":{"sha":"dac159c4","branch":"master"},"sherpa":{"sha":"1759eade","branch":"master"},"sun":{"sha":"12739cd4","branch":"master"}}

**Comment by ariel-phet** [comment]
@pixelzoom as discussed, not necessary that we pass long string test for publication, but it does seem odd that the layout changes. Anything to investigate here?

**Comment by pixelzoom** [comment]
I'll have a look.

**Comment by pixelzoom** [comment]
I added a bit of code to center everything on the screen.  Commits to master and 1.2 branch went a little weird, so ignore the commit messages above. 

Here's a screenshot of the fix, run with "dev" query parameter to show the "safe" zone of the screen (red rectangle).  Note that everything is centered in the red rectangle.

![screenshot_24](https://cloud.githubusercontent.com/assets/3046552/10347316/7ac65782-6cf0-11e5-9505-61931a40923f.png)

This was a relatively trivial change, and I don't feel the need to verify in another RC version. @ariel-phet let me know if you feel otherwise, and I'll keep this open for regression testing. Otherwise please close it.

**Comment by ariel-phet** [comment]
Sounds good, closing
