### ISSUE TITLE
Unclear word choice in "Solute Amount" scale description

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/molarity#217]
For https://github.com/phetsims/QA/issues/464. Related to https://github.com/phetsims/molarity/issues/116.

I think the word choice in the "Solute Amount" section of "Beaker Solution Controls" in Molarity is unclear. The word choice is:

Description | Range for Moles
-- | --
{{max amount of}} | 1.000 moles
{{a lot of}} | 0.850 to 0.950 moles
{{a bunch of}} | 0.650 to 0.800 moles
{{some}} | 0.450 to 0.600 moles
{{a low amount of}} | 0.200 to 0.400 moles
{{a little}} | 0.001 to 0.150 moles
{{no}} | 0.000 moles

- I don't understand why {{a little}} is less than {{a low amount of}}.
- {{some}} could technically be used for any value other than {{no}}.
- I don't understand why {{a bunch of}} is less than {{a lot of}}.

I think something like this would make more sense:

Description | Range for Moles
-- | --
{{max amount of}} | 1.000 moles
{{a very high amount of}} | 0.850 to 0.950 moles
{{a high amount of}} | 0.650 to 0.800 moles
{{a medium amount of}} | 0.450 to 0.600 moles
{{a small amount of}} | 0.200 to 0.400 moles
{{a very small amount of}} | 0.001 to 0.150 moles
{{no}} | 0.000 moles

**Comment by terracoda** [comment]
@lmulhall-phet, great feedback. Descriptions for scales are a challenge, and I think in this sim @Matthew-phet and I were trying to strike a balance between casual, fun, words that still give a sense of increasing and decreasging quantity.

The sim is very simple and playful and colorful. In addition, there is an exact value mode when precision is needed. So rough ideas, rather than super precise words, are the goal for his sim. That said, the scale should still provide a logical sense of increasing and decreasing.

@Matthew-phet and @lmulhall-phet, what do think about the following options?

1.  Swap "a low amount of" and "a little"
Description | Range for Moles
-- | --
{{max amount of}} | 1.000 moles
{{a lot of}} | 0.850 to 0.950 moles
{{a bunch of}} | 0.650 to 0.800 moles
{{some}} | 0.450 to 0.600 moles
{{a little}} | 0.200 to 0.400 moles
{{a low amount of}} | 0.001 to 0.150 moles
{{no}} | 0.000 moles

2.  Replace "a low amount of" with "a little", and put a new option in to indicate the range before zero ("no solute").
Description | Range for Moles
-- | --
{{max amount of}} | 1.000 moles
{{a lot of}} | 0.850 to 0.950 moles
{{a bunch of}} | 0.650 to 0.800 moles
{{some}} | 0.450 to 0.600 moles
{{a little}} | 0.200 to 0.400 moles
{{a bit of}} or {{a pinch of}} or {{a tiny bit of}} | 0.001 to 0.150 moles
{{no}} | 0.000 moles

@lmulhall-phet, I think we are intentionally trying to avoid the longish "amount of" phrasing.

**Comment by Matthew-phet** [comment]
Yeah those changes @terracoda look good, personally I like {{a tiny bit of}} the most but I am also okay with {{a bit of}}

**Comment by terracoda** [comment]
@lmulhall-phet, while your concerns are valid, these phrases impact other parts of the design - minimal changes to the phrasing are preferred.

**2.  Replace "a low amount of" with "a little", and add "a tiny bit of" to indicate the range before zero ("no solute").**

Description | Range for Moles
-- | --
{{max amount of}} | 1.000 moles
{{a lot of}} | 0.850 to 0.950 moles
{{a bunch of}} | 0.650 to 0.800 moles
{{some}} | 0.450 to 0.600 moles
{{a little}} | 0.200 to 0.400 moles
{{a tiny bit of}} | 0.001 to 0.150 moles
{{no}} | 0.000 moles

@jessegreenberg, do you think this swap will be straight forward? 

I'm thinking that "a low amount of" and "a tiny bit of" are similar enough in phrasing that we shouldn't run into any conflicts with other phrasing in other parts of the design (i.e., responses,  dynamic states).

**Comment by terracoda** [comment]
@lmulhall-phet, please add any further concerns you might have about this decision. We can keep them in mind for future designs.

**Comment by lmulhall-phet** [comment]
As long as other people aren't confused by the word choice, I think it's fine. I was just worried that it might be confusing.

**Comment by jessegreenberg** [comment]
I think that would be a straight forward change, usages of these strings all go through a single function. Ill proceed with it.

**Comment by jessegreenberg** [comment]
Change was made in the above commit. As far as I can tell, these strings are used in the screen summary, and in the aria-valuetext.
![image](https://user-images.githubusercontent.com/6396244/72027850-80534480-324e-11ea-963b-f8163f57a9a4.png)

![image](https://user-images.githubusercontent.com/6396244/72027863-8812e900-324e-11ea-8802-9382d831cd8e.png)

@terracoda can you please review to make sure this description is working as expected and hasn't introduced other problems?

**Comment by terracoda** [comment]
Apologies @jessegreenberg, I verified this on Thursday, and forgot to post. The strings all look good to me, too.
