### ISSUE TITLE
Checkbox is playing the same audio twice and magnifying the volume

### ISSUE THREAD

**Issue by samreid** [phetsims/molarity#229]
@jbphet and I discovered this while working on https://github.com/phetsims/wave-interference/issues/483.  We discovered that Molarity uses the sonified Checkbox, then also additionally adds its own sound like so:

```js
  const solutionValuesCheckbox = new Checkbox( solutionValuesLabel, valuesVisibleProperty, {
    maxWidth: 175,
    tandem: tandem.createTandem( 'solutionValuesCheckbox' ),

    // a11y
    accessibleName: showValuesString,
    helpText: solutionValuesHelpTextString
  } );
  solutionValuesCheckbox.touchArea = Shape.rectangle( solutionValuesCheckbox.left, solutionValuesCheckbox.top - 15, solutionValuesCheckbox.width + 5, solutionValuesCheckbox.height + 30 );

  // sound generator for check box
  const uncheckedClip = new SoundClip( checkboxUncheckedSound, {
    enableControlProperties: [ new InvertedBooleanProperty( model.resetInProgressProperty ) ]
  } );
  soundManager.addSoundGenerator( uncheckedClip );
  const checkedClip = new SoundClip( checkboxCheckedSound );
  soundManager.addSoundGenerator( checkedClip );
  valuesVisibleProperty.lazyLink( value => {
    if ( value ) {
      checkedClip.play();
    }
    else {
      uncheckedClip.play();
    }
  } );
```

The effect is that the checkbox volume is loud like on the left instead of quieter like on the right:

![image](https://user-images.githubusercontent.com/679486/76114157-b4bf5480-5fa2-11ea-936e-309ba1621c57.png)

However, since this sim has been through design review and QA, we may actually want the boosted checkbox volume.  This could be accomplished by changing the default levels in Checkbox.  The extraneous code below should be remove in any case.

@jbphet asked for this issue so he can review the checkbox volume levels with the sound team.

**Comment by jbphet** [comment]
I've removed the redundant sound generation and the difference in volume has gone away.

I'm going to make the following two calls and close this issue.  @samreid - feel free to reopen if you disagree with these and we can revisit.
+ This difference is subtle and does not warrant a maintenance release
+ This situation does not call for us to re-review the volume level of the checkbox because that level was already approved in sims without this problem, such as Gravity Force Lab and Gravity Force Lab Basics.
