### ISSUE TITLE
User request: same degrees of precision for solution concentration

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/molarity#28]
Request from user received 3/10 to have the precision for the Molarity "solution concentration" be the same as concentration meter in Concentration.

> It would be nice if both simulations used the same degrees of precision when performing calculations.  
![capture](https://cloud.githubusercontent.com/assets/5090275/13678066/0fe63ade-e6aa-11e5-8be5-ed022a66ad36.PNG)
![capture2](https://cloud.githubusercontent.com/assets/5090275/13678065/0fe150f0-e6aa-11e5-8688-8ce6201bddf4.PNG)

**Comment by pixelzoom** [comment]
I believe we used 2 decimal places to match the number of decimal places for volume. That would need to be checked with the design team.

This would be a trivial to implement. Change line 51 of ConcentrationDisplay to:

``` var VALUE_DECIMAL_PLACES = 3;```

**Comment by pixelzoom** [comment]
Since the list of solutes is identical in the 2 sims, this may be a reasonable request.

**Comment by oliver-phet** [comment]
Assigning to @ariel-phet for thoughts and priority.

**Comment by amyh-phet** [comment]
@ariel-phet  To get 4 sig figs in the molarity calculation, you would need to read both moles and volume to 4 sig figs.  In the Molarity sim, this would mean that any value below 1.000 moles would be recorded to 4 decimal places (eg. 0.2000 mol instead of the current 0.20 mol).  

If we stick with 3 sig figs, then the moles and volume would need to be recorded to 3 decimal places if below 1.00 mol or L.    I might be tempted to go with  3 sig figs as I don't know that reading concentration to 4 sig figs is really necessary in either of these sims.

**Comment by ariel-phet** [comment]
I emailed the teacher who sent the original request for a bit more info. Once I get a response, @amyh-phet can hash out if any changes should be made

**Comment by ariel-phet** [comment]
@pixelzoom haven't heard back from the teacher, but I would go with @amyh-phet comment

> My thought is this: if we aren't worried about sig figs too much, then read concentration to 4 sig figs in both sims. Consider changing the mole and volume amounts in Molarity to read to 3 decimal places if below 1.00 mol or L and display 1 mol or L as 1.00. This will be slightly inconsistent with sig fig rules but less obvious.

If you have some time where you decide to tackle https://github.com/phetsims/concentration/issues/49 maybe this is also a good low priority task to tackle at the same time.

**Comment by pixelzoom** [comment]
@amyh-phet  and @ariel-phet, I took a quick look at this, and it's non-trivial to meet the requirements specified in https://github.com/phetsims/molarity/issues/28#issuecomment-215298255. There's no ability for the sliders to change the number of decimal places based on their current value.  Would it be a problem to use 3 decimal places for all slider values?

Another question... Do you want any change to the range values shown on the ends of the sliders and the concentration display? Or are they fine as is. (They seem fine to me.)

**Comment by pixelzoom** [comment]
I'm also confused by this requirement:
> read concentration to 4 sig figs in both sims.

Do you mean 3 decimal places? Or do you really mean sig figs?  If you mean sig figs, then that requires a change to the Concentration sim, because it does not read to 4 sig figs, it reads to 3 decimal places.  Leading zeros are not counted with significant figures.  And if you really mean significant figures, that's going to be a problem in a lot of places, because PhET's common UI components (sliders, numeric displays, etc) are configured to show a specific number of decimal places, not a specific number of significant figures.

**Comment by amyh-phet** [comment]
@pixelzoom 
Would the following be a set of reasonable changes?

1) Read concentration to 3 decimal places in both Concentration and Molarity sims.
2) Read all slider values to 3 decimal places.
3) Leave range values on sliders as shown.

I think this is the best compromise to meet the user request given current UI component structure.

**Comment by pixelzoom** [comment]
Yes, that will work.

**Comment by pixelzoom** [comment]
Since this sim is tight on horizontal space, going to 3 decimal places created some layout problems. I had to fiddle with the horizontal spacing a bit, and test repeatedly with `?stringTest=double`.

@amyh-phet Here's a dev version. Anything to change?
http://www.colorado.edu/physics/phet/dev/html/molarity/1.3.0-dev.1/molarity_en.html

If all looks well, I'll proceed with integrating the changes into a maintenance release (1.2.5).

**Comment by amyh-phet** [comment]
@pixelzoom   Looks good.

**Comment by pixelzoom** [comment]
Molarity 1.2.5 has been deployed, http://phet.colorado.edu/en/simulation/molarity.
I spot checked the English version and a few translations.

@amyh-phet Please verify. If everything looks OK, please assign to @oliver-phet so that he can notify the user who requested this change.

**Comment by amyh-phet** [comment]
@pixelzoom    Looks okay.

**Comment by oliver-phet** [comment]
User notified. Closing.
