### ISSUE TITLE
For interviews Wed. April 10th

### ISSUE THREAD

**Issue by terracoda** [phetsims/molarity#77]
@emily-phet and @Matthew-phet, since there are 2 interviews schedule for Wednesday April 10th, I opened this issue, so that @zepumph and @twant know that they will need to port the best/latest working described version to the sonification wrapper and to publish a dev link here in this issue.

For work on GFLB, I typically ask @zepumph to use the latest (or best) working version at his end-of-day Tuesday, so I can identify any potential issues (my Wednesday morning) before interviews take place.

I like to make Brianna aware of any known issues and any specific design questions I have before the interviews.

I add resources and comments to this google doc to help interviewer prepare:
https://docs.google.com/document/d/1dxM6ZGuqnsSsrbEm1fKLHTrNJ-xVWL4moVnmbMuMq4g/edit#heading=h.jfvlhxxade2t

**Comment by terracoda** [comment]
@Matthew-phet and @emily-phet, assigning to you so you can re-assign to @twant and @zepumph when appropriate.

**Comment by zepumph** [comment]
@twant and I worked this afternoon to go over the design doc and make sure things are looking good. We then ported the latest into the sonification wrapper. I did a spot check and things seems good to me (as far as I can tell) so I published a new version. Tagging @jbphet and @terracoda because I bet they want to have a look listen and feel before tomorrow.

https://phet-dev.colorado.edu/html/phet-io-wrapper-sonification/1.0.0-dev.110/phet-io-wrapper-sonification/sonification.html

P.S. There was a bit of trouble with the phet-io version, to be tracked in https://github.com/phetsims/sun/issues/496 but that is why there is more than one commit above.

**Comment by terracoda** [comment]
@zepumph, Thanks! That means @emily-phet and @Matthew-phet (and I) can review it today! Awesome!

**Comment by jbphet** [comment]
Thanks @zepumph.  @Ashton-Morris, @emily-phet checked this over today with respect to the sound design implementation and all looks good.

**Comment by pixelzoom** [comment]
Looks like this has been reviewed, and April 10 is long past.  @jbphet can this issue be close?
